feat(app): :sparkles: add listen
mackignacio/rango pull request #2
Opened 2023-08-03 17:11 UTC by renzocabarios

## Changes

- Add listen #1

2023-08-03 17:22 UTC, mackignacio requested changes

2023-08-03 17:22 UTC, mackignacio commented on src/app.ts
> +  http.createServer(app).listen(port, () => {
Try to replace the `app` in `http.createServer(app)` with the `this` keyword. Remove the `app: RequestListener` also in the function parameters in `listen`. Only the `port` must remain as a parameter.

2023-08-03 17:22 UTC, mackignacio commented on src/app.ts
> +  http.createServer(app).listen(port, () => {
Try doing this instead.

```ts
function listen() {
  const server = http.createServer(this)
  return server.listen.apply(server, arguments)
}
```

2023-08-03 17:27 UTC, renzocabarios commented on src/app.ts
> +  http.createServer(app).listen(port, () => {
Where does ""

> Try doing this instead.
> 
> ```ts
> function listen() {
>   const server = http.createServer(this)
>   return server.listen.apply(server, arguments)
> }
> ```

where does "this" refer to?

2023-08-04 10:53 UTC, mackignacio commented on src/app.ts
> +  http.createServer(app).listen(port, () => {
The "this" in this context is the "app" instance of RangoJS.

2023-08-04 13:12 UTC, mackignacio commented
Please do also update the `README.md` file for each code that has the `http.createServer` method.

2023-08-04 13:31 UTC, renzocabarios commented on src/app.ts
> +const listen: RangoApp["listen"] = (...args) => {
## Reference
- https://bobbyhadz.com/blog/typescript-outer-value-this-shadowed-by-this-container#:~:text=The%20error%20"An%20outer%20value,scope%20(the%20class%20instance).

 "'this' implicitly has type 'any' because it does not have a type annotation.ts(2683)" occurs when I use function
One of the solutions I've found is to switch to const

Although my approach works, it will take out the consistency of the code structure.

2023-08-04 13:42 UTC, mackignacio commented on src/app.ts
> +const listen: RangoApp["listen"] = (...args) => {
Did you try this approach?

```ts
function listen(this: RangoApp) {
    // code logic
}
```

2023-08-04 16:36 UTC, mackignacio requested changes

2023-08-04 16:50 UTC, mackignacio approved these changes

2023-08-04 16:52 UTC, merged